name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  aws-access-key-id:
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
  aws-region:
    description: 'AWS_REGION'
    required: true    
outputs:
  service-token:
    description: 'The service token of this custom cloudformation resource'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-region }}
